# Generated by Django 4.1.6 on 2023-02-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_category_listing_description_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='in_Watchlist',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='commerce_pict/'),
        ),
    ]
