# Generated by Django 4.1.6 on 2023-02-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_in_watchlist_alter_comments_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='in_Watchlist',
        ),
        migrations.AddField(
            model_name='user',
            name='in_Watchlist',
            field=models.BooleanField(default='False'),
        ),
    ]
