# Generated by Django 4.1.6 on 2023-02-25 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_in_watchlist_user_in_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidd',
            name='item',
        ),
        migrations.RemoveField(
            model_name='user',
            name='in_Watchlist',
        ),
        migrations.AddField(
            model_name='bidd',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctions.listing'),
        ),
        migrations.CreateModel(
            name='In_Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_Watchlist', models.BooleanField(default='False')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_auction', to='auctions.listing')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_Watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
