# Generated by Django 4.1.6 on 2023-02-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bidd_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidd',
            name='message',
        ),
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
